# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2017 by Cyberhouse GmbH
  project: Doctrine ORM for TYPO3
  version: 1.0
  release: 1.0.0-alpha
  latex_documents:
  - - Index
  html_theme_options:
    github_repository: cyberhouse/typo3-doctrine-orm
    github_branch: master
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - http://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - http://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...
